@baseUrl = http://localhost:3000/api/v1
@contentType = application/json

### [1] Login (Obter JWT Token)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "user32@example.com",
  "password": "senhaSegura123"
}

###
@auth_token = {{login.response.body.data.accessToken}}

### [2] Criar Usuário
# @name createUser
POST {{baseUrl}}/users
Content-Type: {{contentType}}
Authorization: Bearer {{auth_token}}

{
  "email": "user32@example.com",
  "password": "senhaSegura123",
  "perfilId": "4988bada-794e-48a2-b78e-a88328c324c6"
}

### [3] Listar Usuários (Se implementado)
GET {{baseUrl}}/users
Authorization: Bearer {{auth_token}}