version: "3.8"

services:
  postgres:
    image: postgres:15.1-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  sckeledraw:
    image: excalidraw/excalidraw:latest
    container_name: sckeledraw
    ports:
      - "8091:80"

volumes:
  db_data:
